services:
  - name: frontend
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    env:
      - key: NODE_ENV
        value: production

  - name: backend
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    env:
      - key: NODE_ENV
        value: production
